esphome:
  name: "${name}"
  friendly_name: Apollo AIR-1
  comment: Apollo AIR-1
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "ApolloAutomation.AIR-1"
    version: "${version}"

  min_version: 2025.2.0
  on_boot:
    priority: 500
    then:
      - lambda: |-
          id(deep_sleep_1).set_sleep_duration(id(deep_sleep_sleep_duration).state * 60 * 60 * 1000);
      - if:
          condition:
            or:
              - binary_sensor.is_on: ota_mode
              - switch.is_on: prevent_sleep
          then:
             - lambda: |- 
                ESP_LOGW("Apollo", "Preventing Deep Sleep Due To OTA On Boot");
                id(deep_sleep_1).prevent_deep_sleep(); 
  on_shutdown:
    - light.turn_off: rgb_light

dashboard_import:
  package_import_url: github://ApolloAutomation/AIR-1/Integrations/ESPHome/AIR-1_BLE.yaml
  import_full_config: false

ota:
  - platform: esphome
    password: "apolloautomation"
    id: ota_esphome

bluetooth_proxy:
  active: true
esp32_ble_tracker:
  scan_parameters:
    active: false

wifi:
  ap:
    ssid: "Apollo AIR1 Hotspot"

packages:
  core: !include Core.yaml