name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 5 * * 1"
    
jobs:
  build:
    name: ${{ env.DEVICE_NAME }}
    runs-on: ubuntu-latest
    env:
      DEVICE_NAME: AIR-1
    steps:
      - uses: actions/checkout@v4
      - name: Build Firmware
        uses: esphome/build-action@v3.0.0
        id: esphome-build
        with:
          yaml_file: Integrations/ESPHome/${{ env.DEVICE_NAME }}.yaml
          version: 'latest'
          cache: true
      - name: Move generated files to output
        run: |
          mkdir -p output/${{ env.DEVICE_NAME }}
          mv ${{ steps.esphome-build.outputs.name }}/* output/${{ env.DEVICE_NAME }}/
          echo ${{ steps.esphome-build.outputs.version }} > output/${{ env.DEVICE_NAME }}/version
      - name: Alter manifest path
        run: |
          sed -i 's/${{ steps.esphome-build.outputs.name }}\//\/${{ env.DEVICE_NAME }}\//g' output/${{ env.DEVICE_NAME }}/manifest.json
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: build-${{ env.DEVICE_NAME }}
          path: output
          retention-days: 1

  deploy:
    if: contains(fromJSON('["workflow_dispatch", "push", "schedule"]'), github.event_name) && github.ref == 'refs/heads/main'
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
